### ISSUE TITLE
Chaining Handlers

### ISSUE THREAD

**Issue by anupavanm** [RagtimeWilly/WhiteRabbit#1]
I am trying to implement a scenario:
1) Publishers send a message into a queue called - "TaskQueue"
--
I would like the consumer take the message and process it with 3 handlers
like:
 1) TransformData  2)  DBUpdation  3) LogResultsToFile

I want to chain these handlers like this:

                _builder
                    .RegisterHandlerChain()
                    .StartWith<TransformDatahandler>()
                    .Then<DBUpdation Handler>()
                    .Then<LogResultsToFileHandler>();

I should be able to create a workflow - for chaining the handlers

What do you think the appropriate data structure to store the workflow ?

**Comment by RagtimeWilly** [comment]
Hi anupavanm,

I've updated the `IMessageHander` interface to be generic to allow you to chain handlers this way.

So you should now be able to implement handlers along the lines of:

```
class TransformDataHandler : IMessageHandler
{
    private readonly IMessageHandler _innerHandler;

    public TransformDataHandler(IMessageHandler innerHandler)
    {
        _innerHandler = innerHandler;
    }

    public void Handle<T>(T msg)
    {
        var data = // transform your data here
        _innerHandler.Handle(data);
    }
}

class UpdateDBHandler : IMessageHandler
{
    private readonly IMessageHandler _innerHandler;
    private readonly IDatabase _db;

    public UpdateDBHandler(IMessageHandler innerHandler, IDatabase db)
    {
        _innerHandler = innerHandler;
        _db = db;
    }

    public void Handle<T>(T msg)
    {
        var data = msg as TransformedDataType;

        _db.Save(data);

        _innerHandler.Handle(data);
    }
}

class LoggingHandler : IMessageHandler
{
    private readonly ILogger _logger;

    public LoggingHandler(ILogger logger)
    {
        _logger = logger;
    }

    public void Handle<T>(T msg)
    {
        var data = msg as TransformedDataType;

        _logger.Write(data);
    }
}
```

Your above registration should then work correctly. 

You could also implement a single command handler and use the dispatching handler to route the message type to it (see [wiki](https://github.com/RagtimeWilly/WhiteRabbit/wiki/Internally-dispatching-messages)):

```
class Handler : ICommandHandler<MessageType>
{
    private readonly ITransformer _transformer;
    private readonly IDatabase _db;
    private readonly ILogger _logger;

    public Handler(ITransformer transformer, IDatabase db, ILogger logger)
    {
        _transformer = transformer;
        _db = db;
        _logger = logger;
    }

    public void Handle(MessageType msg)
    {
        var data = _transformer.Transform(msg);
        _db.Save(data);
        _logger.Write(data);
    }
}
```

**Comment by anupavanm** [comment]
Thanks a lot.

I implemented the way you suggested by chaining the handlers like this:

(Binding the handlers dynamically)

        static void Main(string[] args)
        {
            var builder = new ContainerBuilder();

            //Registering Handlers

            List<String> lstHandlers = new List<string>();
            lstHandlers.Add("WhiteRabbit.Consumer.TransformDataHandler");
            lstHandlers.Add("WhiteRabbit.Consumer.UpdateDBHandler");
            lstHandlers.Add("WhiteRabbit.Consumer.LoggingHandler");


            Type[] handlers2 = new Type[lstHandlers.Count];
            for(int i = 0; i < lstHandlers.Count; i++)
            {
                handlers2[i] = Type.GetType(lstHandlers[i]);

            }

            builder.RegisterHandlerChainAs(handlers2);

            var container = builder.Build();

            IConnectionFactory cf = new ConnectionFactory
            {
                HostName = "localhost",
                VirtualHost = "/",
                Port = 5672,
                UserName = "xyzr",
                Password = "xyzr"

            };

            string _queueName = "WhiteRabbit.ABQueue";

            IModelFactory mf = new ModelFactory(cf);


            using (var scope = container.BeginLifetimeScope())
            {
                var handlersFromAutoFac = scope.Resolve<IMessageHandler>();

                WhiteRabbitConsumer _consumer = new WhiteRabbitConsumer(handlersFromAutoFac, mf, _queueName, null);

                Task.Run(() => _consumer.Start(true));
            }



            Console.ReadLine();
        }
    }


    class TransformDataHandler : IMessageHandler
    {
        private readonly IMessageHandler _innerHandler;

        public TransformDataHandler(IMessageHandler innerHandler)
        {
            _innerHandler = innerHandler;
        }

        public void Handle<T>(T msg) 
        {
            var eventMsg = msg as BasicDeliverEventArgs;

            JsonSerializer js = new JsonSerializer();

            var data = js.Deserialize<string>(eventMsg.Body);

            Console.WriteLine("TransformDataHandler # " + data);

            _innerHandler.Handle(data);
        }


    }
